### ISSUE TITLE
Documentation for Magento2.Templates.ThisInTemplate rule

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento-coding-standard#108]
### Description
Right now the only one option to use helpers inside blocks - is following code:
`$this->helper(<helper_class>)`, but this Magento2.Templates.ThisInTemplate rule complains against it. As result - we have to add to ignore Magento2.Templates.ThisInTemplate in many view files.

Examples:
Try to find "Magento2.Templates.ThisInTemplate" in following commit:
https://github.com/magento/magento2/commit/514e3d09df58639a0ab714470b0f825fd7da4516

### Expected behavior
We should not have any complains from static tests when running valid code

### Benefits
We will not have useless disabling of this rule

### Additional information
Option 1: this code example should be added to exception list
Option 2: there should be developed or provided recommended solution how to avoid it

**Comment by lenaorobei** [comment]
@ihor-sviziev thanks raising this question. 

First of all we need to define correct recommendation here. On the one hand the use of helpers in is general discouraged, on the other hand we have legacy code that requires significant refactoring in order to archive this.

Do we want to change sniff behavior and allow `$this->helper(<helper_class>)` or we want to suppress such line for now and refactor in future?

Would you be interested in raising this question during next architecture discussion?

**Comment by ihor-sviziev** [comment]
Hi @lenaorobei,
Unfortunately I'll not be able present on next architecture discussion. Could you raise this question instead of me?
Thank you

**Comment by lenaorobei** [comment]
Sure, I'll do that.

**Comment by lenaorobei** [comment]
This issue was discussed during architecture discussion https://github.com/magento/architecture/issues/183. Notes:
- The use of helpers is in general discouraged.
- `Magento2.Templates.ThisInTemplate` rule should remain the same.  
- `$this->helper(<helper_class>)` code should be refactored and blocks contain all necessary dependencies.

I suggest adding documentation for`ThisInTemplateSniff.md` like [ForeachArrayMergeSniff.md](https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md) and describe this recommendation.

I'm going to change purpose of this ticket to adding `.md` page with `How to Fix` section.

**Comment by lenaorobei** [comment]
magento/magento-coding-standard#119
