### ISSUE TITLE
[New Rule] Use Yoda Conditions

### ISSUE THREAD

**Issue by matthiashamacher** [magento/magento-coding-standard#137]
### Rule
Use Yoda Conditions to avoid assignments inside a condition statement.

### Reason
With Yoda Conditions it is not possible to assign a variable inside a condition statement, which improves the code quality because it prevents possible assignment errors.

### Implementation
Some other Frameworks, such as Symfony, are using Yoda Conditions and have checks for them.

**Comment by Vinai** [comment]
Even though I personally favor yoda style comparison, I think a rule for this would be too restrictive. 
The reasons for this are the following.
Many developers find yoda style equality checks harder to reason about because in their mind the comparison is done the other way around.
In my experience, such accidental assignments where extremely rare and never got past a code review. Nowadays they would be caught by tests, too.
Making coding guidelines too restrictive can discourage contribution. I think allowing for personal coding style preferences in the small is more encouraging.

**Comment by lenaorobei** [comment]
I agree with @Vinai here. It is more about personal preferences not about the code style. I do understand you intention, but we don't want to enforce developers to use yoda conditions and limit somehow their personal preferences.

Sorry, going to close this PR.
