### ISSUE TITLE
Misleading message for constant comment

### ISSUE THREAD

**Issue by krisdante** [magento/magento-coding-standard#164]
### Preconditions
The following code comes from Image component:
```
    /**
     * Default font size
     */
    const DEFAULT_FONT_SIZE = 15;
```

### Steps to reproduce
Test with phpcs 
`vendor/bin/phpcs --standard=Magento2 lib/internal/Magento/Framework/Image`

### Expected result
It shall pass

### Actual result
```
FILE: 
lib/internal/Magento/Framework/Image/Adapter/AbstractAdapter.php
----------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------
 65 | WARNING | Constants must have short description if they add information beyond what the constant name supplies.
----------------------------------------------------------------------------------------------------------------------
```

This is misleading information. The code has a description. Also the constant is self-explanatory.

The test checks if the comment is not equal to the variable itself. That leads to situation that the comment needs to be rephrased to something like "Default size for the font" just to pass this test,

**Comment by lenaorobei** [comment]
@krisdante please see my comment here https://github.com/magento/magento-coding-standard/issues/163#issuecomment-566109514

This is the expected behavior. There is no need to duplicate the constant name in the DocBlock.

Documentation: https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#constants

> That leads to situation that the comment needs to be rephrased to something like "Default size for the font" just to pass this test

If the short description adds no additional information beyond what the constant name already supplies, the short description **must be omitted**.
